### PR TITLE
Swift 4.2

### PR DESCRIPTION
**Pull request by yonat**

### CODE REVIEW

**Comment by petkrein** [comment]
@3lvis: Please merge! The Fork looks good. 
Thank you

**Comment by 3lvis** [comment]
Sorry for the delay!

**Comment by petkrein** [comment]
You saved my day!

**Comment by yonat** [comment]
Thanks, now just need to `pod trunk push`.

**Comment by 3lvis** [comment]
Is out https://cocoapods.org/pods/DATASource

**Comment by petkrein** [comment]
@3lvis Thanks, the compatibility display should also be updated:
bildschirmfoto 2018-12-03 um 16 39 59

**Pull request merged**
