### PR TITLE
Support transient property as sectionName

### LINKED ISSUE #69: Support of transient property for sectionName
Transient property for sectionName does not supported for now.
When I use 'firstLetter' (transient property) as sectionName in DATASource initializer I got error:
`'Invalid keypath firstLetter passed to setPropertiesToFetch:'`
There is an issue in default implementation of [UIDataSourceTableView.sectionIndexTitlesForTableView:](https://github.com/3lvis/DATASource/blob/master/Source/DATASource%2BUITableViewDataSource.swift#L37). I suppose this method should detect is property transient and should not execute request when property is transient. Or maybe this metnod should notify developer somehow that when using transient property he must implement DATASourceDelegate.sectionIndexTitlesForDataSource: in this case.

### PR DESCRIPTION
**Pull request by zarv1k**
Fix #69 

See changeset [7351842](https://github.com/3lvis/DATASource/commit/735184266ef5c2b72d34a3ad3340711e84e8cdf1) for reproduce the issue, [555678d](https://github.com/3lvis/DATASource/commit/555678d7535e233af808f43f617c63f0de95b389) - fixes the issue.
But I suppose the default implementation of UITableViewDataSource.sectionIndexTitlesForTableView(_:) should be like in [ea3c945
](https://github.com/3lvis/DATASource/commit/ea3c94577aee58f70c0e1f97f18a0b5db94ddecf)

@3lvis could you please check this out and test with transient and managed properties as well.

### CODE REVIEW

**Comment by zarv1k** [comment]
Found the issue with sort within one section with this changes.

**Comment by 3lvis** [comment]
>Found the issue with sort by count within one section with this changes.

What do you mean? Could you explain, please?

**Comment by 3lvis** [comment]
This looks good @zarv1k! It's awesome that we can replace all of that code with just `self.fetchedResultsController.sectionIndexTitles`. 👏

**Comment by zarv1k** [comment]
> What do you mean? Could you explain, please?

https://vimeo.com/167657891
In modified example that I provide in this PR there are two sort descriptors used. And the second one does not applied because the first sort descriptor is by name (not by 'firstLetterOfName' because we can't sort by transient property). This not expected behavior is from SQL 'ORDER BY' nature. I tried to apply custom string function to apply in first descriptor by a part (first letter) of 'name' but no luck, Core Data with SQL storage does not support custom string functions.

**Comment by 3lvis** [comment]
Oh damn! I'll rever this one until we find a solution :)

**Comment by Sorix** [comment]
Transient property sorting is very important by my mind, for example if you want to group items by month without storing month in database (only NSDate usually stored).

If Core Data has issues with «COUNT» maybe it will be better to specify var in DATASource configuration (e.g.: `var supportTransient: Bool`) where we can enable transient support by specifying that after DATASource initialization?

`NSFetchedResultsController` supports sectioning by transient properties out of the box, it is very strange if DATASource won’t have support of that.

**Pull request merged**
