### PR TITLE
Add configuration of animations with convenience constructor

### PR DESCRIPTION
**Pull request by zarv1k**
In my project using DATASource I want to have ability to configure row animations.
It would be great that DATASource will support the feature.

### CODE REVIEW

**Comment by zarv1k** [comment]
Forgot to change collection view constructor

**Comment by zarv1k** [comment]
Changed constructor

**Comment by 3lvis** [comment]
Hi @zarv1k,

Nice addition! I think this could be done as a parameter instead of having it in the initalizer though.

**Comment by zarv1k** [comment]
@3lvis, Animations configuration dictionary is optional public property. Should I change anything else in addition to remove of my convenience initializer for merge this PR?

**Comment by 3lvis** [comment]
@zarv1k I'll remove the convenience :) Thanks for this addition 👏

**Comment by 3lvis** [comment]
Shipped, thanks!

https://github.com/3lvis/DATASource/releases/tag/5.7.0

**Comment by zarv1k** [comment]
@3lvis, thank you for awesome library and your fast feedback ;)

**Comment by 3lvis** [comment]
Thank god I disabled this thing.

**Pull request merged**
